// Generated by https://quicktype.io

export interface MetroStationDTO {
  StationUID:         string;
  StationID:          string;
  StationName:        StationName;
  StationAddress:     string;
  BikeAllowOnHoliday: boolean;
  SrcUpdateTime:      Date;
  UpdateTime:         Date;
  VersionID:          number;
  StationPosition:    StationPosition;
  LocationCity:       string;
  LocationCityCode:   string;
  LocationTown:       string;
  LocationTownCode:   string;
}

export interface StationName {
  Zh_tw: string;
  En:    string;
}

export interface StationPosition {
  PositionLon: number;
  PositionLat: number;
  GeoHash:     string;
}
